version: "3.7"
services:
  first-react-blog:
    container_name: react-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
